name: Next.js Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: nekomasa-next-blog

      - name: Build Next.js app
        run: npm run build
        working-directory: nekomasa-next-blog

      - name: Copy CNAME file to build output
        run: cp CNAME nekomasa-next-blog/out/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: nekomasa-next-blog/out

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
