name: Version Assets and Deploy

on:
  push:
    branches:
      - master # Your GitHub Pages source branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Ensure this matches your script's compatibility

    - name: Run asset versioning script
      run: node scripts/version-assets.js

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Automated: Versioned assets and updated references" || echo "No changes to commit"
        git push
